### ISSUE TITLE
Missing title for <iframe> tag; "lang" and/or "xml:lang" attribute for html tag; HTML title for project

### ISSUE THREAD

**Issue by Xpx22** [BME-MIT-IET/iet-hf-2022-ietify#3]
Missing title attribute for <iframe> tag under test>url.html
Missing "lang" and/or "xml:lang" attribute for the tag under test>url.html
Missing html title under test>url.html

**Comment by Hooder** [comment]
Bug fixed on [9918a74](https://github.com/BME-MIT-IET/iet-hf-2022-ietify/commit/9918a74f4cb49ce8d9b52c16dc57e7a8df34b358)
