### ISSUE TITLE
implement bdd testing 

### ISSUE THREAD

**Issue by Xpx22** [BME-MIT-IET/iet-hf-2022-ietify#7]
implement bdd tests

Xpx22 parts: 
success for path
fail for path
success for params
Full URL test
Clear query test

Hooder parts:
fail for params
success for path and params
fail for path and params
Relative URL test
Case sensitivity test

**Comment by Xpx22** [comment]
implemented first part
Commit #6 
Commit #10

**Comment by Hooder** [comment]
implemented remaining part
Commit for code: #10 
Commit for doc: #6
